import SidebarLink from "./components/SidebarLink";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen flex">
          <div className="w-64 bg-slate-900 h-full text-white flex flex-col gap-4 p-8">
            <h2 className="text-xl font-bold mb-4">Admin Panel</h2>
            <SidebarLink href="/" title="Dashboard" />
            <SidebarLink href="/createAccount" title="Create Account" />
            <SidebarLink href="/userTable" title="User Table" />
          </div>
          <div className="flex-[1]">{children}</div>
        </div>
      </body>
    </html>
  );
}
